local_ubuntu_14.4:
  ip: '10.0.0.7'
  user: 'gal'
  password: '1'
  accessPoint: True

local_ubuntu_15.4:
  ip: '10.0.0.3'
  user: 'gal'
  password: '1'
  accessPoint: True

ubuntu_test_1:
  ip: '10.0.0.7'
  user: 'gal'
  password: '1'
  accessPoint: False

ubuntu_test_2:
  ip: '10.0.0.3'
  user: 'gal'
  password: '1'
  accessPoint: False

ubuntu_test:
  ip: '10.18.134.73'
  user: 'root'
  password: '123456'
